"""add code to assessments

Revision ID: 1301a106b47a
Revises: 69916f7a373b
Create Date: 2026-05-18 09:54:07.546239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1301a106b47a'
down_revision = '69916f7a373b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessments_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
