"""empty message

Revision ID: 28f695c9b57b
Revises: ef46fd7f76de
Create Date: 2026-04-13 20:19:21.342606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f695c9b57b'
down_revision = 'ef46fd7f76de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer_subjects',
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_id', 'subject_id', name='uq_trainer_subject')
    )
    with op.batch_alter_table('trainer_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainer_subjects_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainer_subjects_trainer_id'), ['trainer_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessments_term'), ['term'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_term'))
        batch_op.drop_column('term')

    with op.batch_alter_table('trainer_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainer_subjects_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_trainer_subjects_subject_id'))

    op.drop_table('trainer_subjects')
    # ### end Alembic commands ###
