"""Add attendance session and record models

Revision ID: 303e5e331d7e
Revises: c700a13f45c3
Create Date: 2026-05-13 10:44:10.025268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303e5e331d7e'
down_revision = 'c700a13f45c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('current_token', sa.String(length=512), nullable=False),
    sa.Column('session_code', sa.String(length=16), nullable=False),
    sa.Column('qr_seed', sa.String(length=256), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('allowed_radius_meters', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('regeneration_interval', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_sessions_code', ['session_code'], unique=False)
        batch_op.create_index('idx_attendance_sessions_token', ['current_token'], unique=False)
        batch_op.create_index('idx_attendance_sessions_trainer_status', ['trainer_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_current_token'), ['current_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_session_code'), ['session_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_trainer_id'), ['trainer_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('attendance_session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_hash', sa.String(length=256), nullable=True),
    sa.Column('browser_info', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('distance_from_trainer', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendance_session_id', 'student_id', name='uq_session_student_attendance')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_records_session', ['attendance_session_id'], unique=False)
        batch_op.create_index('idx_attendance_records_status', ['status'], unique=False)
        batch_op.create_index('idx_attendance_records_student', ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_attendance_session_id'), ['attendance_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_student_id'), ['student_id'], unique=False)

    op.create_table('attendance_token_history',
    sa.Column('attendance_session_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('token_hash', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_token_history', schema=None) as batch_op:
        batch_op.create_index('idx_token_history_hash', ['token_hash'], unique=False)
        batch_op.create_index('idx_token_history_session', ['attendance_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_token_history_attendance_session_id'), ['attendance_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_token_history_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_token_history_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_token_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_token_history_token_hash'))
        batch_op.drop_index(batch_op.f('ix_attendance_token_history_token'))
        batch_op.drop_index(batch_op.f('ix_attendance_token_history_attendance_session_id'))
        batch_op.drop_index('idx_token_history_session')
        batch_op.drop_index('idx_token_history_hash')

    op.drop_table('attendance_token_history')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_status'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_attendance_session_id'))
        batch_op.drop_index('idx_attendance_records_student')
        batch_op.drop_index('idx_attendance_records_status')
        batch_op.drop_index('idx_attendance_records_session')

    op.drop_table('attendance_records')
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_session_code'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_module_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_current_token'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_course_id'))
        batch_op.drop_index('idx_attendance_sessions_trainer_status')
        batch_op.drop_index('idx_attendance_sessions_token')
        batch_op.drop_index('idx_attendance_sessions_code')

    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
