"""empty message

Revision ID: 45e67c2b9d37
Revises: add_course_id_to_enrollments
Create Date: 2026-04-19 20:19:43.431905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45e67c2b9d37'
down_revision = 'add_course_id_to_enrollments'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('term_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('module_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_enrollments_course_id'), ['course_id'], unique=False)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('enrollment_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('assessment_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('student_subjects', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('course_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('student_subjects', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('assessment_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('enrollment_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('course_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_course_id'))
        batch_op.alter_column('module_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('student_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.alter_column('term_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
