"""add code column to all entity tables

Revision ID: 69916f7a373b
Revises: 0b66bedd2aaa
Create Date: 2026-05-18 09:25:33.345101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69916f7a373b'
down_revision = '0b66bedd2aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_institutions_code'), ['code'], unique=True)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_modules_code'), ['code'], unique=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_code'), ['code'], unique=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=True)

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_trainers_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainers_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
