"""new Stuff

Revision ID: 6f0e697b66e2
Revises: bb125e817efa
Create Date: 2026-04-19 19:43:19.979949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f0e697b66e2'
down_revision = 'bb125e817efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_terms_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_terms_start_date'), ['start_date'], unique=False)

    op.create_table('announcements',
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_institution_id'), ['institution_id'], unique=False)

    op.create_table('trainer_courses',
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainer_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainer_courses_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trainer_courses_trainer_id'), ['trainer_id'], unique=False)

    op.create_table('announcement_reads',
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcement_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_reads_announcement_id'), ['announcement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_reads_user_id'), ['user_id'], unique=False)

    op.create_table('scores',
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('feedback', sa.String(length=1000), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_enrollment_id'), ['enrollment_id'], unique=False)

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_module_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('competency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competency_records_competency_id'))
        batch_op.drop_index(batch_op.f('ix_competency_records_student_id'))

    op.drop_table('competency_records')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_competency_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_student_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surveys_user_id'))

    op.drop_table('surveys')
    with op.batch_alter_table('dashboard_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_metrics_module_id'))

    op.drop_table('dashboard_metrics')
    with op.batch_alter_table('portfolio_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_evidence_competency_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_evidence_student_id'))

    op.drop_table('portfolio_evidence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_evidence',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('competency_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('portfolio_evidence_competency_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('portfolio_evidence_student_id_fkey')),
    sa.ForeignKeyConstraint(['verified_by'], ['trainers.id'], name=op.f('portfolio_evidence_verified_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('portfolio_evidence_pkey'))
    )
    with op.batch_alter_table('portfolio_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_evidence_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_evidence_competency_id'), ['competency_id'], unique=False)

    op.create_table('dashboard_metrics',
    sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('average_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mastery_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('at_risk_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('dashboard_metrics_module_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_metrics_pkey'))
    )
    with op.batch_alter_table('dashboard_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_metrics_module_id'), ['module_id'], unique=False)

    op.create_table('surveys',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('perceived_usefulness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('perceived_ease_of_use_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('behavioral_intention_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('surveys_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('surveys_pkey'))
    )
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surveys_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('competency_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('alerts_competency_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('alerts_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alerts_pkey'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_competency_id'), ['competency_id'], unique=False)

    op.create_table('competency_records',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('competency_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mastery_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], name=op.f('competency_records_competency_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('competency_records_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('competency_records_pkey'))
    )
    with op.batch_alter_table('competency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competency_records_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competency_records_competency_id'), ['competency_id'], unique=False)

    op.create_table('attendance',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('attendance_module_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('attendance_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attendance_pkey'))
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_module_id'), ['module_id'], unique=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_enrollment_id'))
        batch_op.drop_index(batch_op.f('ix_scores_assessment_id'))

    op.drop_table('scores')
    with op.batch_alter_table('announcement_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_reads_announcement_id'))

    op.drop_table('announcement_reads')
    with op.batch_alter_table('trainer_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainer_courses_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_trainer_courses_course_id'))

    op.drop_table('trainer_courses')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_institution_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_department_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_creator_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_course_id'))

    op.drop_table('announcements')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_start_date'))
        batch_op.drop_index(batch_op.f('ix_terms_is_active'))
        batch_op.drop_index(batch_op.f('ix_terms_end_date'))

    op.drop_table('terms')
    # ### end Alembic commands ###
