"""this

Revision ID: 7979f9f41ee0
Revises: 1301a106b47a
Create Date: 2026-05-20 09:44:28.267883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7979f9f41ee0'
down_revision = '1301a106b47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessments_code'), ['code'], unique=True)

    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_attendance_sessions_subject'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_documents_subject'))
        batch_op.create_index(batch_op.f('ix_documents_subject_id'), ['subject_id'], unique=False)

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_institutions_code'), ['code'], unique=True)

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_modules_code'), ['code'], unique=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_code'), ['code'], unique=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=True)

    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_trainers_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainers_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_subject_id'))
        batch_op.create_index(batch_op.f('idx_documents_subject'), ['subject_id'], unique=False)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_code'))
        batch_op.drop_column('code')

    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_attendance_sessions_subject'), ['subject_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
