"""empty message

Revision ID: 8032cd093002
Revises: 45e67c2b9d37
Create Date: 2026-04-19 20:45:26.939381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8032cd093002'
down_revision = '45e67c2b9d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    op.create_table('dashboard_metrics',
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('mastery_rate', sa.Float(), nullable=False),
    sa.Column('at_risk_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_metrics_module_id'), ['module_id'], unique=False)

    op.create_table('alerts',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('competency_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_student_id'), ['student_id'], unique=False)

    op.create_table('competency_records',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('competency_id', sa.UUID(), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competency_records_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competency_records_student_id'), ['student_id'], unique=False)

    op.create_table('course_subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_evidence',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('competency_id', sa.UUID(), nullable=True),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_evidence_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_evidence_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('recorded_at')

    with op.batch_alter_table('portfolio_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_evidence_student_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_evidence_competency_id'))

    op.drop_table('portfolio_evidence')
    op.drop_table('course_subjects')
    with op.batch_alter_table('competency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competency_records_student_id'))
        batch_op.drop_index(batch_op.f('ix_competency_records_competency_id'))

    op.drop_table('competency_records')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_student_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_competency_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('dashboard_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_metrics_module_id'))

    op.drop_table('dashboard_metrics')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_module_id'))

    op.drop_table('attendance')
    # ### end Alembic commands ###
