"""new Stuff

Revision ID: abcc6606e5c5
Revises: 6f0e697b66e2
Create Date: 2026-04-19 19:58:26.048990
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abcc6606e5c5'
down_revision = '6f0e697b66e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('term_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('assessment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_marks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pass_marks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.alter_column('module_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('competency_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_assessments_student_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_term'))
        batch_op.drop_index(batch_op.f('ix_assessments_trainer_id'))
        batch_op.create_index(batch_op.f('ix_assessments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_term_id'), ['term_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('assessments_trainer_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('assessments_student_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'terms', ['term_id'], ['id'])
        batch_op.drop_column('score')
        batch_op.drop_column('status')
        batch_op.drop_column('trainer_id')
        batch_op.drop_column('student_id')
        batch_op.drop_column('term')
        batch_op.drop_column('performance_level')
        batch_op.drop_column('source')
        batch_op.drop_column('recorded_at')


    # Ensure at least one course exists
    conn = op.get_bind()
    result = conn.execute(sa.text("SELECT id FROM courses LIMIT 1;")).fetchone()
    if not result:
        # Insert a dummy course
        conn.execute(sa.text("INSERT INTO courses (id, department_id, name, cbet_level, created_at, updated_at) VALUES ('00000000-0000-0000-0000-000000000001', NULL, 'Dummy Course', 'Level 1', NOW(), NOW());"))
        course_id = '00000000-0000-0000-0000-000000000001'
    else:
        course_id = result[0]

    result = conn.execute(sa.text("SELECT id FROM terms LIMIT 1;")).fetchone()
    if not result:
        conn.execute(sa.text("INSERT INTO terms (id, name, start_date, end_date, is_active, created_at, updated_at) VALUES ('00000000-0000-0000-0000-000000000001', 'Dummy Term', NOW(), NOW(), TRUE, NOW(), NOW());"))
        term_id = '00000000-0000-0000-0000-000000000001'
    else:
        term_id = result[0]

    conn.execute(sa.text(f"UPDATE assessments SET course_id = '{course_id}' WHERE course_id IS NULL;"))
    conn.execute(sa.text(f"UPDATE assessments SET term_id = '{term_id}' WHERE term_id IS NULL;"))
    conn.execute(sa.text("UPDATE assessments SET name = 'Untitled' WHERE name IS NULL;"))
    conn.execute(sa.text("UPDATE assessments SET assessment_type = 'exam' WHERE assessment_type IS NULL;"))
    conn.execute(sa.text("UPDATE assessments SET total_marks = 0 WHERE total_marks IS NULL;"))

    nulls = conn.execute(sa.text("SELECT COUNT(*) FROM assessments WHERE course_id IS NULL OR term_id IS NULL OR name IS NULL OR assessment_type IS NULL OR total_marks IS NULL;")).scalar()
    if nulls > 0:
        raise Exception('Migration aborted: Some assessments rows still have NULLs in required columns.')

    # Now set columns to NOT NULL
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.alter_column('course_id', nullable=False)
        batch_op.alter_column('term_id', nullable=False)
        batch_op.alter_column('name', nullable=False)
        batch_op.alter_column('assessment_type', nullable=False)
        batch_op.alter_column('total_marks', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('performance_level', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('term', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('trainer_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assessments_student_id_fkey'), 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('assessments_trainer_id_fkey'), 'trainers', ['trainer_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_assessments_term_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_course_id'))
        batch_op.create_index(batch_op.f('ix_assessments_trainer_id'), ['trainer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_term'), ['term'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_student_id'), ['student_id'], unique=False)
        batch_op.alter_column('competency_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('module_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('weight')
        batch_op.drop_column('pass_marks')
        batch_op.drop_column('total_marks')
        batch_op.drop_column('assessment_type')
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('term_id')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
