"""Add competency assessment_tasks and performance_levels; add assessment.performance_level

Revision ID: bb125e817efa
Revises: 28f695c9b57b
Create Date: 2026-04-18 17:48:57.205041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb125e817efa'
down_revision = '28f695c9b57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performance_level', sa.Integer(), nullable=True))

    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('performance_levels', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.drop_column('performance_levels')
        batch_op.drop_column('assessment_tasks')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('performance_level')

    # ### end Alembic commands ###
