"""new tables

Revision ID: c700a13f45c3
Revises: 2f0304d54b95
Create Date: 2026-05-13 10:29:10.626378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c700a13f45c3'
down_revision = '2f0304d54b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('staff_attendance',
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_attendance_term_id'), ['term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_attendance_trainer_id'), ['trainer_id'], unique=False)

    op.create_table('lesson_plans',
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('covered_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_plans_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_plans_term_id'), ['term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_plans_trainer_id'), ['trainer_id'], unique=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_enrollments_term_id'), ['term_id'], unique=False)
        batch_op.create_foreign_key(None, 'terms', ['term_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_enrollments_term_id'))
        batch_op.drop_column('term_id')

    with op.batch_alter_table('lesson_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_plans_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_plans_term_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_plans_subject_id'))

    op.drop_table('lesson_plans')
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_attendance_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_staff_attendance_term_id'))

    op.drop_table('staff_attendance')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_uploaded_by'))

    op.drop_table('documents')
    # ### end Alembic commands ###
