"""add_lesson_plans_staff_attendance

Revision ID: d1a3c7257054
Revises: 3d9c2f4b7a11
Create Date: 2026-05-01 02:24:54.697261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a3c7257054'
down_revision = '3d9c2f4b7a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_attendance',
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_attendance_term_id'), ['term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_attendance_trainer_id'), ['trainer_id'], unique=False)

    op.create_table('lesson_plans',
    sa.Column('trainer_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('covered_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_plans_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_plans_term_id'), ['term_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_plans_trainer_id'), ['trainer_id'], unique=False)

    with op.batch_alter_table('student_subjects', schema=None) as batch_op:
        batch_op.alter_column('student_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('subject_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subjects', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('lesson_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_plans_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_plans_term_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_plans_subject_id'))

    op.drop_table('lesson_plans')
    with op.batch_alter_table('staff_attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_attendance_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_staff_attendance_term_id'))

    op.drop_table('staff_attendance')
    # ### end Alembic commands ###
