"""empty message

Revision ID: d83c225364aa
Revises: f9bf8a0ac8a2
Create Date: 2026-04-11 17:32:44.988165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83c225364aa'
down_revision = 'f9bf8a0ac8a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_subjects',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', name='uq_student_subject')
    )
    with op.batch_alter_table('student_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_subjects_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_subjects_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_subjects_subject_id'))
        batch_op.drop_index(batch_op.f('ix_student_subjects_student_id'))

    op.drop_table('student_subjects')
    # ### end Alembic commands ###
