"""empty message

Revision ID: ef46fd7f76de
Revises: d83c225364aa
Create Date: 2026-04-11 17:49:43.509516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef46fd7f76de'
down_revision = 'd83c225364aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_permissions', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
