"""add_enrollment_term_id

Revision ID: fdd7761907fd
Revises: d1a3c7257054
Create Date: 2026-05-05 19:17:20.888510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd7761907fd'
down_revision = 'd1a3c7257054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('term_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_enrollments_term_id'), ['term_id'], unique=False)
        batch_op.create_foreign_key(None, 'terms', ['term_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_enrollments_term_id'))
        batch_op.drop_column('term_id')

    # ### end Alembic commands ###
